language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-polymer-gulp' ]; then cd .. && eval "mv $currentfolder generator-polymer-gulp" && cd generator-polymer-gulp; fi
